name: Build and upload with compose

on:
  push:
    branches: 
      - main
    paths:
      - compose.yaml
  pull_request:
    branches: 
      - main
    paths:
      - compose.yaml

  workflow_dispatch: # akkor fut le újra ha változik a compose fájl, különben manuálisan is elindítható githubon

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker compose build
        docker login ghcr.io -u borsodi-koppany -p ${{ secrets.GHCR_TOKEN }}
        docker compose push